services:
  portainer-ce:
    container_name: portainer
    image: portainer/portainer-ce
    ports:
      - '8000:8000'
      - '9000:9000'
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./portainer_data:/data"
    networks:
      - main-network

networks:
  main-network:
    external: true 
